# Welcome to Jekyll!

# Name of website
title: Visionlearning

url: "https://cavidano.github.io/visionlearning/"
port: 4001

# Exclude
exclude:
  - readme.md
  - src/*
  - .babelrc
  - .gitignore
  - node_modules/*
  - Gemfile
  - Gemfile.lock
  - nyc-core-framework.code-workspace
  - package-lock.json
  - package.json
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - tearsheet.html

webrick:
  headers:
    Access-Control-Allow-Origin: "*"