# Welcome to Jekyll!

# Name of website
title: Visionlearning

description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
port: 4001

# Exclude
exclude:
  - readme.md
  - src/*
  - .babelrc
  - .gitignore
  - node_modules/*
  - Gemfile
  - Gemfile.lock
  - nyc-core-framework.code-workspace
  - package-lock.json
  - package.json
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - tearsheet.html

webrick:
  headers:
    Access-Control-Allow-Origin: "*"


  # Comment (exclude) for versioning
  # - version/*`
