# Name of website
title: Visionlearning

url: "https://cavidano.github.io/visionlearning"
port: 4001

# Exclude
exclude:
  - README.md
  - node_modules
  - src
  - package.json
  - package-lock.json
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js

# Collections
collections:
  docs:
    output: true
    permalink: /docs/:path/

  updates:
    output: true
    permalink: /docs/updates/:year/:month/:day/:title/

#Headers
webrick:
  headers:
    Access-Control-Allow-Origin: "*"