# Welcome to Jekyll!

# Name of website
title: Visionlearning

baseurl: ""
url: "http://127.0.0.1:4001"
port: 4001

# Exclude
exclude:
  - readme.md
  - src/*
  - .babelrc
  - .gitignore
  - node_modules/*
  - Gemfile
  - Gemfile.lock
  - nyc-core-framework.code-workspace
  - package-lock.json
  - package.json
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js
  - tearsheet.html

webrick:
  headers:
    Access-Control-Allow-Origin: "*"