# Name of website
title: Visionlearning

url: "https://cavidano.github.io/visionlearning"
port: 4001

# Exclude
exclude:
  - README.md
  - node_modules
  - src
  - package.json
  - package-lock.json
  - webpack.common.js
  - webpack.dev.js
  - webpack.prod.js

webrick:
  headers:
    Access-Control-Allow-Origin: "*"